In [2]:
import os
import sys
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency
os.chdir('..')
from src.utils import descriptive_statistics

In [3]:
file_path = "C:/Users/hp/Documents/10 academy/Week 3/AlphaCare-Insurance-Solutions/data/MachineLearningRating_v3.txt"
df = pd.read_csv(file_path,sep='|',low_memory=False)

In [4]:
df.head(5)

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [5]:
df.dropna(inplace=True)

In [6]:
 def missing_values_table(df):
    # Total missing values
        mis_val = df.isnull().sum()

    # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)

    # dtype of missing values
        mis_val_dtype = df.dtypes

    # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent, mis_val_dtype], axis=1)

    # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns={0: 'Missing Values', 1: '% of Total Values', 2: 'Dtype'})

    # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
        mis_val_table_ren_columns.iloc[:, 1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)

    # Print some summary information
        print("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"
             "There are " + str(mis_val_table_ren_columns.shape[0]) +
             " columns that have missing values.")

    # Return the dataframe with missing information
        return mis_val_table_ren_columns

In [10]:
print(f"Missing values: {missing_values_table(df)}")

Your selected dataframe has 52 columns.
There are 52 columns that have missing values.
Missing values:                           Missing Values  % of Total Values    Dtype
UnderwrittenCoverID                    0                NaN    int64
PolicyID                               0                NaN    int64
TransactionMonth                       0                NaN   object
IsVATRegistered                        0                NaN     bool
Citizenship                            0                NaN   object
LegalType                              0                NaN   object
Title                                  0                NaN   object
Language                               0                NaN   object
Bank                                   0                NaN   object
AccountType                            0                NaN   object
MaritalStatus                          0                NaN   object
Gender                                 0                NaN   object
Country                                0                NaN   object
Province                               0                NaN   object
PostalCode                             0                NaN    int64
MainCrestaZone                         0                NaN   object
SubCrestaZone                          0                NaN   object
ItemType                               0                NaN   object
mmcode                                 0                NaN  float64
VehicleType                            0                NaN   object
RegistrationYear                       0                NaN    int64
make                                   0                NaN   object
Model                                  0                NaN   object
Cylinders                              0                NaN  float64
cubiccapacity                          0                NaN  float64
kilowatts                              0                NaN  float64
bodytype                               0                NaN   object
NumberOfDoors                          0                NaN  float64
VehicleIntroDate                       0                NaN   object
CustomValueEstimate                    0                NaN  float64
AlarmImmobiliser                       0                NaN   object
TrackingDevice                         0                NaN   object
CapitalOutstanding                     0                NaN   object
NewVehicle                             0                NaN   object
WrittenOff                             0                NaN   object
Rebuilt                                0                NaN   object
Converted                              0                NaN   object
CrossBorder                            0                NaN   object
NumberOfVehiclesInFleet                0                NaN  float64
SumInsured                             0                NaN  float64
TermFrequency                          0                NaN   object
CalculatedPremiumPerTerm               0                NaN  float64
ExcessSelected                         0                NaN   object
CoverCategory                          0                NaN   object
CoverType                              0                NaN   object
CoverGroup                             0                NaN   object
Section                                0                NaN   object
Product                                0                NaN   object
StatutoryClass                         0                NaN   object
StatutoryRiskType                      0                NaN   object
TotalPremium                           0                NaN  float64
TotalClaims                            0                NaN  float64